#!/bin/bash
# ============================================================
# Script 5: Open Source Manifesto Generator
# Author: Vj038 | Roll No: 24BAI10819
# Course: Open Source Software
# Software Audited: Git
# Description: Asks the user three interactive questions and
#              generates a personalised open source philosophy
#              statement, saving it to a .txt file.
# ============================================================

# --- Alias concept demonstrated via comment ---
# In a real shell session you might define:
#   alias mkmanifesto='./script5_manifesto_generator.sh'
# This lets you run the script with a short memorable name.
# Aliases make frequently used commands faster to type.

echo "=============================================="
echo "   Open Source Manifesto Generator"
echo "   OSS Audit | Roll No: 24BAI10819"
echo "=============================================="
echo ""
echo "  Answer three questions to generate your"
echo "  personalised open source manifesto."
echo ""

# --- Read user input interactively ---
# read -p displays a prompt and stores the answer in a variable

read -p "  1. Name one open-source tool you use every day: " TOOL
echo ""

read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
echo ""

read -p "  3. Name one thing you would build and share freely: " BUILD
echo ""

# --- Validate that all three answers were provided ---
if [ -z "$TOOL" ] || [ -z "$FREEDOM" ] || [ -z "$BUILD" ]; then
    echo "  ERROR: All three questions must be answered."
    exit 1
fi

# --- Generate output filename using current username ---
DATE=$(date '+%d %B %Y')                        # Formatted date
TIME=$(date '+%H:%M:%S')                         # Current time
OUTPUT="manifesto_$(whoami).txt"                 # Output filename

echo "----------------------------------------------"
echo "  Generating your manifesto..."
echo "----------------------------------------------"
echo ""

# --- Compose the manifesto paragraph using string concatenation ---
# Using echo with >> to append each line to the output file
# The > operator creates/overwrites the file
# The >> operator appends to the file

# Create/overwrite file with header
echo "===============================================" > "$OUTPUT"
echo " OPEN SOURCE MANIFESTO"                         >> "$OUTPUT"
echo " Generated by: $(whoami)"                       >> "$OUTPUT"
echo " Roll No: 24BAI10819"                           >> "$OUTPUT"
echo " Date: $DATE | Time: $TIME"                     >> "$OUTPUT"
echo "===============================================" >> "$OUTPUT"
echo ""                                               >> "$OUTPUT"

# Write the personalised manifesto paragraph
echo "My Open Source Manifesto" >> "$OUTPUT"
echo "------------------------" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# String concatenation: combining variables with fixed text
echo "Every day, I rely on $TOOL — a tool built not by a" >> "$OUTPUT"
echo "corporation seeking profit, but by people who believed" >> "$OUTPUT"
echo "that knowledge and code should be shared freely with" >> "$OUTPUT"
echo "the world. To me, freedom means $FREEDOM. That is what" >> "$OUTPUT"
echo "open source represents: the $FREEDOM to use, study," >> "$OUTPUT"
echo "modify, and distribute software without restriction." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "I believe in the philosophy that Linus Torvalds embodied" >> "$OUTPUT"
echo "when he released Git to the world — that the best tools" >> "$OUTPUT"
echo "are built in the open, improved by many hands, and owned" >> "$OUTPUT"
echo "by no one. That is why, if I were to create something" >> "$OUTPUT"
echo "new, I would build $BUILD and share it freely — so that" >> "$OUTPUT"
echo "someone, somewhere, could learn from it, improve it, or" >> "$OUTPUT"
echo "build something even greater on top of it." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "This is what open source means to me." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Signed: $(whoami) | $DATE" >> "$OUTPUT"
echo "===============================================" >> "$OUTPUT"

# --- Confirm file was created and display it ---
echo "  Manifesto saved to: $OUTPUT"
echo ""
echo "----------------------------------------------"

# cat reads and prints the file contents to the terminal
cat "$OUTPUT"

echo "----------------------------------------------"
echo "  Done! Submit '$OUTPUT' as part of your audit."
echo "=============================================="
